### ISSUE TITLE
add uuid5 logic to epss and kev reports

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/arango_cve_processor#12]
https://github.com/muchdogesec/arango_cve_processor/commit/23c61e732929251732034ffe985229fc721d7c7a

**Comment by himynamesdave** [comment]
@fqrious getting

```
  File "/Users/dgreenwood/Documents/repos/dogesec/arango_cve_processor/arango_cve_processor/__main__.py", line 69, in main
    stix_obj = run_all(**args.__dict__)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dgreenwood/Documents/repos/dogesec/arango_cve_processor/arango_cve_processor/__main__.py", line 65, in run_all
    relation_manager.process()
  File "/Users/dgreenwood/Documents/repos/dogesec/arango_cve_processor/arango_cve_processor/managers/base_manager.py", line 160, in process
    uploads.extend(self.relate_multiple(objects))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dgreenwood/Documents/repos/dogesec/arango_cve_processor/arango_cve_processor/managers/cve_kev.py", line 54, in relate_multiple
    id="report--"+uuid.uuid5(config.UUID, content),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/uuid.py", line 728, in uuid5
    hash = sha1(namespace.bytes + bytes(name, "utf-8")).digest()
                ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'property' and 'bytes'
E

```

**Comment by himynamesdave** [comment]
@fqrious i'm now getting

```
python3 -m unittest tests/test_05_00_cve_kev.py
```


```
Traceback (most recent call last):
  File "/Users/dgreenwood/Documents/repos/dogesec/arango_cve_processor/tests/test_05_00_cve_kev.py", line 32, in setUpClass
    subprocess.run([
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', 'arango_cve_processor.py', '--database', 'arango_cve_processor_standard_tests_database', '--relationship', 'cve-kev', '--ignore_embedded_relationships', 'false']' returned non-zero exit status 1.
```
